apiVersion: v1
kind: Service
metadata:
  name: app-service
  # namespace: default
spec:
  type: NodePort
  selector:
    app: simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31516