name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubernetes
        run: |
          cd kubernetesFile
          kubectl apply -f deployment.yaml --server=https://kubernetes.docker.internal:6443 --insecure-skip-tls-verify
